.github/workflows/run-tests.yml, .gitignore, ibm-cloud-secrets-manager-api-v1/ibm_cloud_secrets_manager_api_v1.go, ibm-cloud-secrets-manager-api-v1/ibm_cloud_secrets_manager_api_v1_integration_test.go, ibm-cloud-secrets-manager-api-v1/ibm_cloud_secrets_manager_api_v1_test.go
=> add auth url and create secret conflict test [skip ci]

.github/workflows/create-release.yaml, README.md, common/version.go, go.mod, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_integration_test.go, secretsmanagerv1/secrets_manager_v1_suite_test.go, secretsmanagerv1/secrets_manager_v1_test.go
=> Updated SDK

common/version.go, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_test.go
=> API update

secretsmanagerv1/secrets_manager_v1_integration_test.go
=> fix conflict test

common/version.go, go.mod, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_integration_test.go, secretsmanagerv1/secrets_manager_v1_test.go
https://github.ibm.com/security-services/secrets-manager-project-management/issues/1870
=> Public cert

.github/workflows/run-tests.yml, secretsmanagerv1/secrets_manager_v1_integration_test.go
=> fix workflow yaml

common/headers.go, common/version.go, go.mod, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_test.go
Private endpoint support added
=> Private endpoint support

common/version.go, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_test.go
remove all explicit fields from secret_data
https://github.ibm.com/security-services/secrets-manager-project-management/issues/2966
=> Secret data

secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_integration_test.go, secretsmanagerv1/secrets_manager_v1_test.go
Add integration tests for Kv plugin
=> Issue 3279 - Add integration tests for Kv plugin

common/version.go, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_test.go
https://github.ibm.com/security-services/secrets-manager-project-management/issues/3495
=> Version 1.0.37

secretsmanagerv1/secrets_manager_v1_integration_test.go
Add Cleanup to intergation tests
Change tests to enable parelle runs
=> add Cleanup to Integration tests

common/version.go, go.mod, go.sum, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_integration_test.go, secretsmanagerv1/secrets_manager_v1_test.go
=> VERSION 1.0.45 - Locks

common/version.go, secretsmanagerv1/secrets_manager_v1.go, secretsmanagerv1/secrets_manager_v1_test.go
Signed-off-by: haims <haims@il.ibm.com>
=> User-provided CSR

.bumpversion.cfg, .github/workflows/create-release.yaml, .releaserc, README.md, common/version.go, package.json
Move the repository to use semantic-release to manage future releases
=> update CI to use semantic-release

README.md
=> feat: new SM v2 API release

secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_examples_test.go, secretsmanagerv2/secrets_manager_v2_integration_test.go, secretsmanagerv2/secrets_manager_v2_test.go
=> minor: Adding get secret by name

common/headers.go, secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_examples_test.go, secretsmanagerv2/secrets_manager_v2_integration_test.go, secretsmanagerv2/secrets_manager_v2_suite_test.go, secretsmanagerv2/secrets_manager_v2_test.go
- Custom password generation policy for user-credentials secrets
- Fix service credentials secret (missing fields in response)
=> patch: Custom password generation policy for user-credentials secrets

secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_examples_test.go, secretsmanagerv2/secrets_manager_v2_integration_test.go, secretsmanagerv2/secrets_manager_v2_test.go
- Add List filters: `secret_types`, `match_all_labels`
- Add Expiration date field to `iam_credentials` and `service_credentials` API responses
=> patch: API enhancements

README.md, secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_test.go
add private cert intermediate rotate API
=> patch: support for intermediate CA certificates rotation

go.mod
issue related: https://github.ibm.com/security-services/secrets-manager-project-management/issues/7810
=> Upgrade to Go v1.22

go.mod
=> upgrade go to 1.23

README.md, secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_examples_test.go, secretsmanagerv2/secrets_manager_v2_integration_test.go, secretsmanagerv2/secrets_manager_v2_test.go
Adding support for custom credentials.
=> patch: custom credentials secret type

secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_test.go
Reverts IBM/secrets-manager-go-sdk#123
=> Revert "Add retrieved_at field"

README.md, secretsmanagerv2/secrets_manager_v2.go, secretsmanagerv2/secrets_manager_v2_test.go
Reverts IBM/secrets-manager-go-sdk#125
=> Patch: Revert "Revert "Add retrieved_at field""
